/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Game;

import java.sql.CallableStatement;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


public class DangKy extends javax.swing.JFrame {

    /**
     * Creates new form DangKy
     */
    public DangKy() {
        initComponents();
        setLocationRelativeTo(null);
        
        ImageIcon icon = new ImageIcon("Assets/iconDangki.png");
        setIconImage(icon.getImage());
        
        btnDangKy.setSize(190, 24);
        btnLamLai.setSize(90,24);
        btnDangNhap.setSize(90, 24);
    }
    int quyen = 0;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtTaiKhoan = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMatKhau = new javax.swing.JPasswordField();
        txtTenDN = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnDangKy = new javax.swing.JButton();
        btnDangNhap = new javax.swing.JButton();
        btnLamLai = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Đăng kí tài khoản");
        setBackground(new java.awt.Color(153, 255, 51));

        jPanel1.setLayout(null);

        txtTaiKhoan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtTaiKhoan.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTaiKhoan.setBorder(null);
        txtTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTaiKhoanActionPerformed(evt);
            }
        });
        jPanel1.add(txtTaiKhoan);
        txtTaiKhoan.setBounds(130, 40, 190, 20);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("THÔNG TIN ĐĂNG KÝ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 350, 40);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 102));
        jLabel2.setText("Tên đăng nhập");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 40, 90, 25);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 102));
        jLabel4.setText("Mật khẩu");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 120, 60, 26);

        txtMatKhau.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtMatKhau.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMatKhau.setBorder(null);
        jPanel1.add(txtMatKhau);
        txtMatKhau.setBounds(130, 120, 190, 20);

        txtTenDN.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtTenDN.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTenDN.setBorder(null);
        jPanel1.add(txtTenDN);
        txtTenDN.setBounds(130, 80, 190, 20);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 102));
        jLabel3.setText("Tên Tài khoản");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 80, 84, 25);

        btnDangKy.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnDangKy.setForeground(new java.awt.Color(255, 102, 102));
        btnDangKy.setText("Đăng ký");
        btnDangKy.setBorder(null);
        btnDangKy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangKyActionPerformed(evt);
            }
        });
        jPanel1.add(btnDangKy);
        btnDangKy.setBounds(130, 160, 190, 20);

        btnDangNhap.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnDangNhap.setForeground(new java.awt.Color(255, 102, 102));
        btnDangNhap.setText("Đăng nhập");
        btnDangNhap.setBorder(null);
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });
        jPanel1.add(btnDangNhap);
        btnDangNhap.setBounds(130, 200, 90, 20);

        btnLamLai.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnLamLai.setForeground(new java.awt.Color(255, 102, 102));
        btnLamLai.setText("Làm lại");
        btnLamLai.setBorder(null);
        btnLamLai.setPreferredSize(new java.awt.Dimension(43, 13));
        btnLamLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamLaiActionPerformed(evt);
            }
        });
        jPanel1.add(btnLamLai);
        btnLamLai.setBounds(230, 200, 90, 20);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Documents\\NetBeansProjects\\TH_Game\\Games\\Assets\\Dangki.jpg")); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(0, 0, 350, 250);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTaiKhoanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTaiKhoanActionPerformed

    private void btnLamLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamLaiActionPerformed
        txtTaiKhoan.setText("");
        txtTenDN.setText("");
        txtMatKhau.setText("");
        txtTaiKhoan.requestFocus();    
    }//GEN-LAST:event_btnLamLaiActionPerformed

    private void btnDangKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangKyActionPerformed
        String taikhoan = txtTaiKhoan.getText();
        String tendn = txtTenDN.getText();
        String matkhau = String.valueOf(txtMatKhau.getPassword());
        if (taikhoan.equals ("")|| tendn.equals("") || matkhau.equals("")) {
            JOptionPane.showMessageDialog(this ,"Bạn phải nhập đầy đủ thông tin", "Thông báo",JOptionPane.INFORMATION_MESSAGE   );
            txtTaiKhoan.requestFocus();
        } else {
            String errConnect = Connect.getConnection();
            if (!errConnect.equals("")) {
                JOptionPane.showMessageDialog(this , errConnect, "Lỗi", JOptionPane.ERROR_MESSAGE);                
            } else {
                String sql ="{call ThemUser(?,?,?,?,?)}";
                CallableStatement cstm;
                String kq;
               try {
                   cstm = Connect.conn.prepareCall(sql);
                   cstm.setString(1, taikhoan);
                   cstm.setString(2, tendn);
                   //matkhau = Connect.MD5(matkhau);
                   cstm.setString(3, matkhau);
                   cstm.setInt(4, quyen);
                   cstm.registerOutParameter(5, java.sql.Types.NVARCHAR);
                   cstm.execute();
                   kq = cstm.getString(5);
                   JOptionPane.showMessageDialog(this, kq, "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                   cstm.close();
                   Connect.conn.close();
                   
               }  catch(SQLException ex) {
                    JOptionPane.showMessageDialog(this, "Lỗi: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
               }
            }
        }
        
    }//GEN-LAST:event_btnDangKyActionPerformed

    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
        DangNhap dangNhap = new DangNhap();
        dangNhap.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDangNhapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangKy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangKy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangKy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangKy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DangKy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangKy;
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JButton btnLamLai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtMatKhau;
    private javax.swing.JTextField txtTaiKhoan;
    private javax.swing.JTextField txtTenDN;
    // End of variables declaration//GEN-END:variables

    
}
