/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Game;

import java.sql.CallableStatement;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class JF_AdminInformation extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public JF_AdminInformation() {
        initComponents();
        setLocationRelativeTo(null);
         
        ImageIcon icon = new ImageIcon("Assets/01.png");
        setIconImage(icon.getImage());
        
        reset();
    }
    
    int quyen = 1;
    
    private void reset(){
        txtTenDangNhap.setText("");
        txtTenTaiKhoan.setText("");
        txtMatKhau.setText("");
        
        txtTenDangNhap.requestFocus();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtTenDangNhap = new javax.swing.JTextField();
        txtTenTaiKhoan = new javax.swing.JTextField();
        btnTaoTaiKhoan = new javax.swing.JButton();
        btnCapNhatThongTin = new javax.swing.JButton();
        btnXoaTaiKhoan = new javax.swing.JButton();
        txtMatKhau = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quản lý các tài khoản Quản trị viên");

        jPanel1.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 204));
        jLabel7.setText("MẬT KHẨU");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 140, 68, 15);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 204));
        jLabel9.setText("TÊN TÀI KHOẢN");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(10, 100, 100, 15);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 204));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("QUẢN LÝ TÀI KHOẢN QUẢN TRỊ VIÊN");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(0, 11, 468, 29);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 204));
        jLabel12.setText("TÊN ĐĂNG NHẬP");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(10, 60, 110, 15);

        txtTenDangNhap.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtTenDangNhap.setForeground(new java.awt.Color(204, 51, 0));
        txtTenDangNhap.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtTenDangNhap);
        txtTenDangNhap.setBounds(180, 51, 200, 30);

        txtTenTaiKhoan.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtTenTaiKhoan.setForeground(new java.awt.Color(204, 51, 0));
        txtTenTaiKhoan.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtTenTaiKhoan);
        txtTenTaiKhoan.setBounds(180, 91, 200, 30);

        btnTaoTaiKhoan.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnTaoTaiKhoan.setForeground(new java.awt.Color(51, 102, 255));
        btnTaoTaiKhoan.setText("TẠO TÀI KHOẢN");
        btnTaoTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoTaiKhoanActionPerformed(evt);
            }
        });
        jPanel1.add(btnTaoTaiKhoan);
        btnTaoTaiKhoan.setBounds(180, 246, 200, 23);

        btnCapNhatThongTin.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnCapNhatThongTin.setForeground(new java.awt.Color(51, 102, 255));
        btnCapNhatThongTin.setText("CẬP NHẬT THÔNG TIN");
        btnCapNhatThongTin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatThongTinActionPerformed(evt);
            }
        });
        jPanel1.add(btnCapNhatThongTin);
        btnCapNhatThongTin.setBounds(180, 275, 200, 23);

        btnXoaTaiKhoan.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnXoaTaiKhoan.setForeground(new java.awt.Color(51, 102, 255));
        btnXoaTaiKhoan.setText("XOÁ TÀI KHOẢN");
        btnXoaTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaTaiKhoanActionPerformed(evt);
            }
        });
        jPanel1.add(btnXoaTaiKhoan);
        btnXoaTaiKhoan.setBounds(180, 304, 200, 23);

        txtMatKhau.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtMatKhau.setForeground(new java.awt.Color(204, 51, 0));
        txtMatKhau.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtMatKhau);
        txtMatKhau.setBounds(180, 131, 200, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Documents\\NetBeansProjects\\Games\\Assets\\background02.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-6, -6, 480, 400);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTaoTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoTaiKhoanActionPerformed
        String tendn = txtTenDangNhap.getText();
        String taikhoan = txtTenTaiKhoan.getText();
        String matkhau = String.valueOf(txtMatKhau.getPassword());
        
        if (taikhoan.equals ("")|| tendn.equals("") || matkhau.equals("")) {
            JOptionPane.showMessageDialog(this ,"Bạn phải nhập đầy đủ thông tin", "Thông báo",JOptionPane.INFORMATION_MESSAGE   );
            txtTenDangNhap.requestFocus();
        } else {
            String errConnect = Connect.getConnection();
            if (!errConnect.equals("")) {
                JOptionPane.showMessageDialog(this , errConnect, "Lỗi", JOptionPane.ERROR_MESSAGE);                
            } else {
                String sql ="{call ThemAccount(?,?,?,?,?)}";
                CallableStatement cstm;
                String kq;
               try {
                   cstm = Connect.conn.prepareCall(sql);
                   cstm.setString(1, tendn);
                   cstm.setString(2, taikhoan);
                   //matkhau = Connect.MD5(matkhau);
                   cstm.setString(3, matkhau);
                   cstm.setInt(4, quyen);
                   cstm.registerOutParameter(5, java.sql.Types.NVARCHAR);
                   
                   cstm.execute();
                   kq = cstm.getString(5);
                   JOptionPane.showMessageDialog(this, kq, "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                   cstm.close();
                   Connect.conn.close();
                   
                   reset();
                   
               }  catch(SQLException ex) {
                    JOptionPane.showMessageDialog(this, "Lỗi: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
               }
            }
        }
    }//GEN-LAST:event_btnTaoTaiKhoanActionPerformed

    private void btnCapNhatThongTinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatThongTinActionPerformed
        String tendn = txtTenDangNhap.getText();
        String taikhoan = txtTenTaiKhoan.getText();
        String matkhau = String.valueOf(txtMatKhau.getPassword());
        if (taikhoan.equals ("")|| tendn.equals("") || matkhau.equals("")) {
            JOptionPane.showMessageDialog(this ,"Bạn phải nhập đầy đủ thông tin", "Thông báo",JOptionPane.INFORMATION_MESSAGE   );
            txtTenDangNhap.requestFocus();
        } else {
            String errConnect = Connect.getConnection();
            if (!errConnect.equals("")) {
                JOptionPane.showMessageDialog(this , errConnect, "Lỗi", JOptionPane.ERROR_MESSAGE);
            } else {
                String sql ="{call UpdateAccountAdmin(?,?,?,?,?)}";
                CallableStatement cstm;
                String kq;
                try {
                    cstm = Connect.conn.prepareCall(sql);
                    cstm.setString(1, tendn);
                    cstm.setString(2, taikhoan);
                    //matkhau = Connect.MD5(matkhau);
                    cstm.setString(3, matkhau);
                    cstm.setInt(4, quyen);
                    cstm.registerOutParameter(5, java.sql.Types.NVARCHAR);
                    cstm.execute();
                    kq = cstm.getString(5);
                    JOptionPane.showMessageDialog(this, kq, "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                    cstm.close();
                    Connect.conn.close();
                    
                    reset();
                    
                }  catch(SQLException ex) {
                    JOptionPane.showMessageDialog(this, "Lỗi: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_btnCapNhatThongTinActionPerformed

    private void btnXoaTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaTaiKhoanActionPerformed
        String tendn = txtTenDangNhap.getText();
        String taikhoan = txtTenTaiKhoan.getText();
        String matkhau = String.valueOf(txtMatKhau.getPassword());
        if (taikhoan.equals ("")|| tendn.equals("") || matkhau.equals("")) {
            JOptionPane.showMessageDialog(this ,"Bạn phải nhập đầy đủ thông tin", "Thông báo",JOptionPane.INFORMATION_MESSAGE   );
            txtTenDangNhap.requestFocus();
        } else {
            String errConnect = Connect.getConnection();
            if (!errConnect.equals("")) {
                JOptionPane.showMessageDialog(this , errConnect, "Lỗi", JOptionPane.ERROR_MESSAGE);
            } else {
                String sql ="{call DeleteAccountAdmin(?,?,?,?,?)}";
                CallableStatement cstm;
                String kq;
                try {
                    cstm = Connect.conn.prepareCall(sql);
                    cstm.setString(1, tendn);
                    cstm.setString(2, taikhoan);
                    //matkhau = Connect.MD5(matkhau);
                    cstm.setString(3, matkhau);
                    cstm.setInt(4, quyen);
                    cstm.registerOutParameter(5, java.sql.Types.NVARCHAR);
                    cstm.execute();
                    kq = cstm.getString(5);
                    JOptionPane.showMessageDialog(this, kq, "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                    cstm.close();
                    Connect.conn.close();
                    
                    reset();

                }  catch(SQLException ex) {
                    JOptionPane.showMessageDialog(this, "Lỗi: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_btnXoaTaiKhoanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_AdminInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_AdminInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_AdminInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_AdminInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_AdminInformation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhatThongTin;
    private javax.swing.JButton btnTaoTaiKhoan;
    private javax.swing.JButton btnXoaTaiKhoan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtMatKhau;
    private javax.swing.JTextField txtTenDangNhap;
    private javax.swing.JTextField txtTenTaiKhoan;
    // End of variables declaration//GEN-END:variables
}
