/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Game;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;

/**
 *
 * @author Admin
 */
public class JF_HistoricalGameRatings extends javax.swing.JFrame {

    /**
     * Creates new form JF_HistoricalGameRatings
     */
    public JF_HistoricalGameRatings() {
        initComponents();
        setLocationRelativeTo(null);
         
        ImageIcon icon = new ImageIcon("Assets/05.png");
        setIconImage(icon.getImage());
        
        doKQ();
    }
    
    public void doKQ(){
        jTextArea_Rating.setText(Connect.getConnection());
        if(jTextArea_Rating.getText().equals("")){
            String sql = "SELECT TOP(10) UserMark, Name FROM RESULTS, USERS \n" +
                         "WHERE RESULTS.USERID = USERS.USERID\n" +
                         "ORDER BY RESULTS.UserMark DESC ;";
            Statement stmt;
            String data;
            try {
                stmt = Connect.conn.createStatement();
                try(ResultSet rs = stmt.executeQuery(sql)) {
                    data = "Điểm số\tNgười chơi\n";
                    while(rs.next()){
                        data += rs.getInt("UserMark") + "\t";
                        data += rs.getString("Name");
                        data += "\n";  
                    }
                    jTextArea_Rating.setText(data);
                    rs.close();
                    
                }
                stmt.close();
                Connect.conn.close();
            } catch (SQLException ex) {
                jTextArea_Rating.setText("Lỗi: "+ ex.getMessage());
            }
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_Rating = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Top Các Số Điểm Cao Nhất");

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TOP 10 SỐ ĐIỂM CAO NHẤT");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 11, 529, 43);

        jTextArea_Rating.setColumns(20);
        jTextArea_Rating.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextArea_Rating.setForeground(new java.awt.Color(255, 102, 51));
        jTextArea_Rating.setRows(5);
        jTextArea_Rating.setBorder(null);
        jScrollPane1.setViewportView(jTextArea_Rating);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(330, 60, 190, 230);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Documents\\NetBeansProjects\\Games\\Assets\\background04.jpg")); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(-6, -6, 540, 390);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_HistoricalGameRatings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_HistoricalGameRatings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_HistoricalGameRatings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_HistoricalGameRatings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_HistoricalGameRatings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea_Rating;
    // End of variables declaration//GEN-END:variables
}
