/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Game;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class JF_PlayerGamingHistory extends javax.swing.JFrame {

    /**
     * Creates new form JF_PlayerGamingHistory
     */
    public JF_PlayerGamingHistory() {
        initComponents();
        setLocationRelativeTo(null);
         
        ImageIcon icon = new ImageIcon("Assets/04.png");
        setIconImage(icon.getImage());
        
        doKQ();
        
        //jTextArea_PlayerGamingHistory.setText(""+ );
    }
    
    public void doKQ(){
        jTextArea_PlayerGamingHistory.setText(Connect.getConnection());
        if(jTextArea_PlayerGamingHistory.getText().equals("")){
            String sql = "select * from RESULTS where UserID = '"+ Connect.userID +"'";
            Statement stmt;
            String data;
            try {
                stmt = Connect.conn.createStatement();
                try(ResultSet rs = stmt.executeQuery(sql)) {
                    data = "Thời gian\t\tĐiểm\n";
                    while(rs.next()){
                        data += rs.getString("TimeResult") + "\t";
                        data += rs.getInt("UserMark");
                        data += "\n";
                    }
                    jTextArea_PlayerGamingHistory.setText(data);
                    rs.close();
                }
                stmt.close();
                Connect.conn.close();
            } catch (SQLException ex) {
                jTextArea_PlayerGamingHistory.setText("Lỗi: "+ ex.getMessage());
            }
            
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_PlayerGamingHistory = new javax.swing.JTextArea();
        jButton_Remove = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lịch Sử Chơi Của Bạn");

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LỊCH SỬ LƯỢT CHƠI");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 11, 549, 43);

        jTextArea_PlayerGamingHistory.setColumns(20);
        jTextArea_PlayerGamingHistory.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextArea_PlayerGamingHistory.setForeground(new java.awt.Color(255, 102, 51));
        jTextArea_PlayerGamingHistory.setRows(5);
        jTextArea_PlayerGamingHistory.setBorder(null);
        jScrollPane1.setViewportView(jTextArea_PlayerGamingHistory);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(200, 290, 350, 100);

        jButton_Remove.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jButton_Remove.setForeground(new java.awt.Color(255, 0, 102));
        jButton_Remove.setText("Xoá");
        jButton_Remove.setBorder(null);
        jButton_Remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RemoveActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Remove);
        jButton_Remove.setBounds(140, 340, 60, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Documents\\NetBeansProjects\\Games\\Assets\\background03.jpg")); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(-6, -6, 560, 390);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_RemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RemoveActionPerformed
        int remove = JOptionPane.showConfirmDialog(this, "Có chắc bạn muốn xoá lịch sử chơi Game.", "Thông báo", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if(remove == JOptionPane.YES_OPTION){
            
            String errConnect = Connect.getConnection();
            if(!errConnect.equals("")){
                JOptionPane.showMessageDialog(this, errConnect, "Lỗi", JOptionPane.ERROR_MESSAGE);
            }else{
                String sql = "delete RESULTS where UserID = '"+ Connect.userID +"' ";
                Statement stm;
                try {
                    stm = Connect.conn.createStatement();
                    int row = stm.executeUpdate(sql);
                    JOptionPane.showMessageDialog(this, "Đã xoá "+ row +" dòng lịch sử chơi của bạn", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                    stm.close();
                    Connect.conn.close();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, errConnect, "Lỗi", JOptionPane.ERROR_MESSAGE);
                }
            }
            doKQ();
            
        }
    }//GEN-LAST:event_jButton_RemoveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_PlayerGamingHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_PlayerGamingHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_PlayerGamingHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_PlayerGamingHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_PlayerGamingHistory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Remove;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea_PlayerGamingHistory;
    // End of variables declaration//GEN-END:variables
}
