/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Game;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class JF_SettingUserInformation extends javax.swing.JFrame {

    
    /**
     * Creates new form User
     */
    public JF_SettingUserInformation() {
        initComponents();
        setLocationRelativeTo(null);
         
        ImageIcon icon = new ImageIcon("Assets/03.png");
        setIconImage(icon.getImage());
        
        jTextField_TenDangNhap.setText(""+ Connect.userID);
        jTextField_NameUser1.requestFocus();
    }

    int quyen = 0;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField_TenDangNhap = new javax.swing.JTextField();
        jButton_UpdateAccount = new javax.swing.JButton();
        jPasswordField_Password = new javax.swing.JPasswordField();
        jTextField_NameUser1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Thông Tin User");

        jPanel1.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 0, 204));
        jLabel7.setText("MẬT KHẨU MỚI");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 200, 110, 15);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("CẬP NHẬT THÔNG TIN");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(0, 11, 470, 29);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 0, 204));
        jLabel11.setText("TÊN ĐĂNG NHẬP ");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(10, 80, 110, 20);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 0, 204));
        jLabel12.setText("TÊN TÀI KHOẢN MỚI");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(10, 160, 140, 15);

        jTextField_TenDangNhap.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jTextField_TenDangNhap.setForeground(new java.awt.Color(204, 51, 0));
        jTextField_TenDangNhap.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_TenDangNhap.setBorder(null);
        jTextField_TenDangNhap.setEnabled(false);
        jPanel1.add(jTextField_TenDangNhap);
        jTextField_TenDangNhap.setBounds(220, 71, 200, 30);

        jButton_UpdateAccount.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jButton_UpdateAccount.setForeground(new java.awt.Color(51, 102, 255));
        jButton_UpdateAccount.setText("CẬP NHẬT TÀI KHOẢN");
        jButton_UpdateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_UpdateAccountActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_UpdateAccount);
        jButton_UpdateAccount.setBounds(220, 250, 200, 30);

        jPasswordField_Password.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jPasswordField_Password.setForeground(new java.awt.Color(204, 51, 0));
        jPasswordField_Password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPasswordField_Password.setBorder(null);
        jPanel1.add(jPasswordField_Password);
        jPasswordField_Password.setBounds(220, 190, 200, 30);

        jTextField_NameUser1.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jTextField_NameUser1.setForeground(new java.awt.Color(204, 51, 0));
        jTextField_NameUser1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_NameUser1.setBorder(null);
        jPanel1.add(jTextField_NameUser1);
        jTextField_NameUser1.setBounds(220, 150, 200, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 51));
        jLabel3.setText("User ID không được phép cập nhật ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(220, 100, 200, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Documents\\NetBeansProjects\\Games\\Assets\\background04.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-6, -6, 480, 400);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_UpdateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_UpdateAccountActionPerformed
        String tendn = Connect.userID;
        String taikhoan = jTextField_NameUser1.getText();
        String matkhau = String.valueOf(jPasswordField_Password.getPassword());
        if (taikhoan.equals ("")|| tendn.equals("") || matkhau.equals("")) {
            JOptionPane.showMessageDialog(this ,"Bạn phải nhập đầy đủ thông tin", "Thông báo",JOptionPane.INFORMATION_MESSAGE   );
            jTextField_TenDangNhap.requestFocus();
        } else {
            String errConnect = Connect.getConnection();
            if (!errConnect.equals("")) {
                JOptionPane.showMessageDialog(this , errConnect, "Lỗi", JOptionPane.ERROR_MESSAGE);                
            } else {
                String sql ="{call UpdateUser(?,?,?,?,?)}";
                CallableStatement cstm;
                String kq;
               try {
                   cstm = Connect.conn.prepareCall(sql);
                   cstm.setString(1, tendn);
                   cstm.setString(2, taikhoan);
                   //matkhau = Connect.MD5(matkhau);
                   cstm.setString(3, matkhau);
                   //cstm.setInt(4, 0);
                   cstm.setInt(4, quyen);
                   cstm.registerOutParameter(5, java.sql.Types.NVARCHAR);
                   cstm.execute();
                   kq = cstm.getString(5);
                   JOptionPane.showMessageDialog(this, kq + "\nThông tin chi tiết vừa cập nhật:\nTên đăng nhập: "+tendn+"\nTên tài khoản mới: "+taikhoan+"\nMật khẩu mới: "+matkhau+"", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                   cstm.close();
                   Connect.conn.close();
                   
                   jTextField_NameUser1.setText("");
                   jPasswordField_Password.setText("");
                   jTextField_NameUser1.requestFocus();
                   
               }  catch(SQLException ex) {
                    JOptionPane.showMessageDialog(this, "Lỗi: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
               }
            }
        }
        
    }//GEN-LAST:event_jButton_UpdateAccountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_SettingUserInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_SettingUserInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_SettingUserInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_SettingUserInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_SettingUserInformation().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_UpdateAccount;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField_Password;
    private javax.swing.JTextField jTextField_NameUser1;
    private javax.swing.JTextField jTextField_TenDangNhap;
    // End of variables declaration//GEN-END:variables
}
